from enum import StrEnum


class Command(StrEnum):
    JOIN = "JOIN"
    GUESS = "GUESS"

    # Server-sent commands
    WAITING = "WAITING"
    GAME_START = "GAME_START"
    GUESS_RESULT = "GUESS_RESULT"
    INVALID_GUESS = "INVALID_GUESS"
    OPPONENT_PROGRESS = "OPPONENT_PROGRESS"
    OPPONENT_SOLVED = "OPPONENT_SOLVED"
    GAME_OVER = "GAME_OVER"
    OPPONENT_DISCONNECTED = "OPPONENT_DISCONNECTED"


class InvalidGuessReason(StrEnum):
    NOT_A_WORD = "NOT_A_WORD"
    WRONG_LENGTH = "WRONG_LENGTH"
